### PR TITLE
add git hash in generated source file

### PR DESCRIPTION
**Pull request by t-bltg**
Add the `wrapit` tool git hash in the generated source files, for reproducibility.

### CODE REVIEW

**Comment by grasph** [comment]
@t-bltg please review the changes I made to your PR.

**Comment by t-bltg** [comment]
Hum, the file `version.cmake` seems to be missing in https://github.com/grasph/wrapit/pull/25/commits/e8e9ca9ef8c8eb4d65cd0ebf9528b908616a03fe, so it fails to build.

**Comment by t-bltg** [comment]
I've usde `target_sources` instead, since you cannot use a missing source in `add_executable` (version.cpp), which would be created by the `version` target.

**Comment by grasph** [comment]
The error was still there with your fix. I don't how I missed it before. It works for me with the trick of 6785d2d  commit.

**Comment by t-bltg** [comment]
Odd, this worked on my laptop, and I extra checked by removing `CMAKE_BINARY_DIR` before building `wrapit`.

Anyway, I can confirm that it now builds as expected.

**Comment by t-bltg** [comment]
Thanks !

**Pull request merged**
