### PR TITLE
Rework examples and tests using CMake

### LINKED ISSUE #43: ex001-HelloWorld adds packages to the Julia environment
When I `make` the ex001-HelloWorld example, `CxxWrap` gets added to my Julia environment, which shouldn't happen.

This is the culprit:

```make
CXXWRAP_PREFIX=$(shell julia -e 'import Pkg; haskey(Pkg.dependencies(), Base.UUID("1f15a43c-97ca-5a2a-ae31-89f07a497df4")) || Pkg.add("CxxWrap"); using CxxWrap; print(CxxWrap.prefix_path())')
```

Shouldn't we instead have a `Project.toml` for the example?

### PR DESCRIPTION
**Pull request by graeme-a-stewart**
This PR reworks the ex001 example to work in a different way:

- Use CMake to deal with invoking `wrapit` and then building the library with CxxWrap
- Drive the process using Julia, `build.jl` and the test with `test.jl`

I see various advantages here:

- Out of source tree builds are supported (by default it's a `./build` directory)
- CMake is the recommended way to drive `CxxWrap`, so the example now follows the recommended recipe
- CMake is more robust for cross platform work, rather than invoking shell commands
- Driving from Julia also avoids needing a setup script that modifies the environment, as Julia can setup what's required
- Fixes #43 too!

I think this would also be a nicer, more consistent, way to drive all of the tests.

I took a lot of inspiration from @peremato's Geant4 wrapper package.

I would mark this as WIP at the moment as it would be worth discussing what we want here.

### CODE REVIEW

**Comment by grasph** [comment]
Moving to CMake was on the todo list. So, this work is great.

I will need to spend some time to review what you did and decide what to do with the tests and examples. CMake has also support for  a `test` target we should consider. 

Philippe.

**Comment by graeme-a-stewart** [comment]
Here is a more complete version that shows how the tests can be refactored using CMake.

Most of the build logic is shared in `test/WrapitTestSetup.cmake`. Customisation for each test is achieved just by changing the project name. Each test has a small stub CMake to set the project name and pull in the main setup.

Running `test/runtests.jl` will now:

- Ensure the custom environment is correct (adding CxxWrap if needed)
- Loop over each test running the CMake configure and build step
- Include the Julia test script for each test (now the convention is just to call the `test.jl`)

When run like this it is important that the tests build libraries which do not have symbol clashes as these will cause problems. Therefore the header files for the converted tests are updated.

A small "stand alone" build script is also supplied that will drive the build of any single test, which is useful for developing and debugging new tests.

Excluding the build messages, the relevant output from the test run is like this:

```julia
$ julia --project=. runtests.jl
...
Test Summary:         | Pass  Total  Time
Tests                 |   26     26  4.6s
  TestAccessAndDelete |   13     13  2.8s
  TestCtorDefVal      |    4      4  0.9s
  TestStdString       |    9      9  0.9s
```

Finishing this PR is just a matter of converting the remaining tests in the same way as the three already done.

N.B. A CMake top level test is also added now, allowing one to `cmake --build . --target test`:

```sh
➜  wrapit cmake --build . --target test
[0/1] Running tests...
Test project /Users/graemes/build/wrapit
    Start 1: ex001-HelloWorld
1/2 Test #1: ex001-HelloWorld .................   Passed    2.08 sec
    Start 2: unittests
2/2 Test #2: unittests ........................   Passed    4.10 sec

100% tests passed, 0 tests failed out of 2

Total Test time (real) =   6.18 sec
```

The downside of this is that all the fine grained Julia tests get wrapped up into a single CMake level test - but at least they do run, following the standard pattern (yes, we could break this down into individual tests).

Anyway, before proceeding, is this the direction we agree to take? Let me know @grasph @peremato!

**Comment by graeme-a-stewart** [comment]
Every test can also be run individually as well, e.g., in each test directory just run

```sh
julia --project=.. test.jl
```

But the `runtests.jl` wraps up everything so that it all runs together.

To clarify about the libraries, they are all built separately. They are also loaded separately, *but in the same Julia process* here: https://github.com/grasph/wrapit/blob/7083cca81e9a4a0ecc1139df32807a4191c63269/test/runtests.jl#L31. What I found was that before my refactoring of the names I got this error:

> "Warning: Type 1A already had a mapped type set as AAllocated and const-ref indicator 0 and C++ type name 1A. Hash comparison: old(5859413,0) == new(5859413,0) == true

When I renamed the classes this disappeared.

Just to note it is possible to `run()` each test in a separate Julia process, but then the test output is not so good as the `@test`s don't stack properly for subprocesses, e.g.,:

```julia
...
Test Summary:         | Pass  Total  Time
Tests                 |    3      3  4.3s
  TestAccessAndDelete |    1      1  1.5s
  TestCtorDefVal      |    1      1  1.4s
  TestStdString       |    1      1  1.4s
```

**Comment by grasph** [comment]
I see. Thanks for the clarification.  So far, we have taken the path of forking the process.

I think I prefer the fork option: writing a unit test should be simple, we should not need to bother about name clash, especially we should be able to clone a unit test without need to change all type names. Details on number of passed subtests have little interest from my point of view.

It would be great to get rid of the need of setting `CMAKE_PREFIX_PATH`: I would like to be able in a test directory to do: `mkdir build; cd build; cmake ..; cmake --build .`

I've manage to achieve this with the change in `WrapitTestSetup.cmake` you can see in https://gist.github.com/grasph/80360841af5aeb1fba3229128476ed34 and adding the script `print_cxxwrap_prefix` in the same directory as `WrapitTestSetup.cmake`. Probably that should be factorized with the examples.

It's not clear to me if the script `print_cxxwrap_prefix` should do the bootstrapping or if we should require it to be done explicitly.

**Comment by graeme-a-stewart** [comment]
> I see. Thanks for the clarification. So far, we have taken the path of forking the process.
> 
> I think I prefer the fork option: writing a unit test should be simple, we should not need to bother about name clash, especially we should be able to clone a unit test without need to change all type names. Details on number of passed subtests have little interest from my point of view.

I don't really agree - changing names isn't such a chore and it helps the tests to be more explicit rather than always testing a class `A`. Remember the tests will be looked at by other people as well, not just the original developer.

I also like seeing the individual test results because when a test fails I want to know which one it is. With forking that is obscured.

> 
> It would be great to get rid of the need of setting `CMAKE_PREFIX_PATH`: I would like to be able in a test directory to do: `mkdir build; cd build; cmake ..; cmake --build .`
> 
> I've managed to achieve this with the change in `WrapitTestSetup.cmake` you can see in https://gist.github.com/grasph/80360841af5aeb1fba3229128476ed34 and adding the script `print_cxxwrap_prefix` in the same directory as `WrapitTestSetup.cmake`. Probably that should be factorized with the examples.

That's a great idea! I'll adapt the common CMake to use this.

> 
> It's not clear to me if the script `print_cxxwrap_prefix` should do the bootstrapping or if we should require it to be done explicitly.

IMO, it should bootstrap, so that we achieve the maxim of `mkdir build; cd build; cmake ..; cmake --build .; make --build . --target test`, without surprising the user into needing to prepare other non-standard things.

**Comment by graeme-a-stewart** [comment]
See the latest commit, that adds the support for finding `CxxWrap` directly as you suggested @grasph. With this one can invoke for a test:

```sh
 cmake -S . -B build
 cmake --build build
 cmake --build build --target test
```

and everything works without surprises!

**Comment by grasph** [comment]
I've tested the code and below are my thoughts. I've tested the approaches proposed in each comment and I will commit soon code implementing them.

**Single/multiple process for test**

I agree some test lacks in having more explicit type and function names, but I don't think  requiring names to differ from the ones used in the other independent tests is good constraint: e.g., a good name for a function that adds two numbers is `add` or `sum`, even if these symbols are already used in the other independent tests.

Therefore, I think we should fix the result stacking in the multiple-process approach.

**Test script names**

I prefer to use distinct names for the test scripts, instead the `runtests.jl` generic one. We can keep the `run${PROJECT_NAME}.jl` name scheme, with `PROJECT_NAME` the test/cmake project name.

**Module definition**

I prefer to have the wrapper module defined in a separate file instead of within the script.

**Support for multiple generated files**

In the current cmake examples wrapit produces a single source code file. The `wrapit` generation mode `n_classes_per_file = n`, with n > 0 is more challenging, because it is difficult to predict the list of produced files. `Geant4.jl` handles this using a `GLOB` in cmake. This approach is discouraged by the cmake documentation (see note of https://cmake.org/cmake/help/v3.28/command/file.html#filesystem) and from the test I've made I get the impression is that it does not handle the dependency properly.

The challenge here is that the list of input objects for the library to generate is dynamic. While it's an easy case when using directly `make`, it's not as easy with `cmake`. After searching around on the internet, I think the easiest approach is to run `wrapit` at the configuration step. My proposal is:

   - add an option to `wrapit` to generate a cmake file that defines two variables: one with the list of produced files and one with the list of files their contents depends on. The current wrapit code produces only the first list, written in  `generated_cxx` file;
   - run `wrapit` with `execute_process()` (→ at configuration time)
   - include the cmake file produced by wrapit with a `include()` statement (→ defines variables with the list of generated files and the list of dependencies)
   - uses the `CMAKE_CONFIGURE_DEPENDS` property to express the wrapit step dependencies and trigger reconfiguration when wrapit needs to be rerun.

**Comment by graeme-a-stewart** [comment]
Hi Philippe - thanks for your thoughts, I have some comments interspersed below:

> I've tested the code and below are my thoughts. I've tested the approaches proposed in each comment and I will commit soon code implementing them.

OK, very good - then I won't keep developing this branch, but I am prepared to help if it's useful.

> 
> **Single/multiple process for test**
> 
> I agree some test lacks in having more explicit type and function names, but I don't think requiring names to differ from the ones used in the other independent tests is good constraint: e.g., a good name for a function that adds two numbers is `add` or `sum`, even if these symbols are already used in the other independent tests.
> 
> Therefore, I think we should fix the result stacking in the multiple-process approach.

It's ok with me. When a test block fails it will require re-running that particular test suite separately, but I think we can make this easy to do (it's already done in the few converted tests in this branch).

> 
> **Test script names**
> 
> I prefer to use distinct names for the test scripts, instead the `runtests.jl` generic one. We can keep the `run${PROJECT_NAME}.jl` name scheme, with `PROJECT_NAME` the test/cmake project name.

Agreed.

> 
> **Module definition**
> 
> I prefer to have the wrapper module defined in a separate file instead of within the script.
> 
> **Support for multiple generated files**
> 
> In the current cmake examples wrapit produces a single source code file. The `wrapit` generation mode `n_classes_per_file = n`, with n > 0 is more challenging, because it is difficult to predict the list of produced files. `Geant4.jl` handles this using a `GLOB` in cmake. This approach is discouraged by the cmake documentation (see note of https://cmake.org/cmake/help/v3.28/command/file.html#filesystem) and from the test I've made I get the impression is that it does not handle the dependency properly.

I can confirm that - the problem is that CMake globs at configure time, when there are no files. So one has to run CMake, then build (it fails, but generates the C++ files), then re-run CMake.

> 
> The challenge here is that the list of input objects for the library to generate is dynamic. While it's an easy case when using directly `make`, it's not as easy with `cmake`. After searching around on the internet, I think the easiest approach is to run `wrapit` at the configuration step. My proposal is:
> 
> * add an option to `wrapit` to generate a cmake file that defines two variables: one with the list of produced files and one with the list of files their contents depends on. The current wrapit code produces only the first list, written in  `generated_cxx` file;
> * run `wrapit` with `execute_process()` (→ at configuration time)
> * include the cmake file produced by wrapit with a `include()` statement (→ defines variables with the list of generated files and the list of dependencies)
> * uses the `CMAKE_CONFIGURE_DEPENDS` property to express the wrapit step dependencies and trigger reconfiguration when wrapit needs to be rerun.

OK, I think it's definitely worth trying it that way.

**Comment by grasph** [comment]
Hello @graeme-a-stewart . I've pushed the change in the cmake-example branch of this github: https://github.com/grasph/wrapit/tree/cmake-example.

The cmake scheme is now also implemented in TestStdVector, that uses the on-file-per-class mode.

Have a try and let me know what you think of the change.

**Comment by graeme-a-stewart** [comment]
Hi @grasph - it does seem to work for me. I like the scheme here of getting wrapit to bootstrap at configure time, so that the list of C++ source files are known at the correct time by CMake.

When all of the pieces are in place I can try to use it with my HepMC3.jl project.

**Comment by grasph** [comment]
* I've finalized the changes in ex001-examples including the README.
* I've extended the cmake to more unit tests

Two unit tests produces several libraries, and they were not using the common `make.rules` file. More work would be needed to switch them to `cmake`.

`cmake` seems to me an overkill for the unit tests. It makes writing the build rules harder, add a extra step for the compilation, with no benefit. I would be in favor to keep using plain `make` for the unit tests. 

With the plain `make` option, the code is now also built out of the source directory and there is `setup.sh` sourcing is no more needed.

The most important is to have an example, which will be provided with `ex001-HelloWorld`.  Having the ROOT example eventually migrated to cmake would also be good.

**Comment by grasph** [comment]
All the unit tests that were using the make.rules are now converted to cmake. Only the two unit tests with custom makefiles remain to be converted. It would be good to embed first the contents of WrapitTestSetup.cmake into a function.

I will merge this PR. A new PR can be opened when the migration will be completed.

**Comment by graeme-a-stewart** [comment]
Thanks a lot for working on this @grasph!

**Pull request merged**
